apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8schaos.fullname" . }}
  labels:
    {{- include "k8schaos.labels" . | nindent 4 }}
data:
  app.env: |
    NAMESPACE: {{ .Values.config.namespace }}
    TIME_PERIOD: {{ .Values.config.timePeriod }}